first_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from firstapp import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.homepage),
    path('firstapp/', include('firstapp.urls')),
    path('learnURL/', include('learnURL.urls'))
]

firstapp/urls.py
from django.conf.urls import url
from firstapp import views

urlpatterns = [

    url('home/', views.home , name='home'),
    url('users/', views.users , name='home'),
    url('index',views.index, name='index'),
    url('help/', views.help , name='help'),
    url('formpage/',views.form_name_view),
    url('signup/',views.formdataSave)
]

learnURL/urls.py
from django.conf.urls import url
from learnURL import views

# template tagging
app_name = 'learnURL'
urlpatterns = [
    url('home/',views.index,name='index'),
    url('relative/', views.relative,name='relative'),
    url('other/',views.other,name='other')
]

firstapp/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    top_name = models.CharField(max_length=264,unique=True)

    def __str__(self):
        return self.top_name
class Webpage(models.Model):
    topic = models.ForeignKey(Topic,on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=264,unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name

class Accessrecord(models.Model):
    name = models.ForeignKey(Webpage,on_delete=models.DO_NOTHING)
    date = models.DateField()

    def __str__(self):
        return str(self.date)

class User(models.Model):
    fname = models.CharField(max_length=24)
    lname = models.CharField(max_length=24)
    email = models.EmailField(unique=True)

learnURL/models.py
from django.db import models

# Create your models here.

firstapp/forms.py
from django import forms
from django.core import validators
from firstapp.models import User

def validate_geeks_mail(value):
    if "@gmail.com" in value:
        return value
    else:
        raise forms.ValidationError("This field accepts mail id of google only")

def valiate_descrip(value):
    if len(value) < 20 :
        raise forms.ValidationError("Description should be at least 20 words.")
class FormName(forms.Form):
    name = forms.CharField()
    email = forms.EmailField(validators=[validate_geeks_mail])
    description = forms.CharField(widget=forms.Textarea,validators=[valiate_descrip])
    botcatch = forms.CharField(required=False,widget=forms.HiddenInput)

    def catchbot(self):
        bot = self.cleaned_data['botcatch']
        if len(bot) > 0:
            raise forms.ValidationError("CAUGHT YOU")
        return bot

class NewformPage(forms.ModelForm):
    #def validators can be used here
    # Each model will have its own class meta
    class Meta:
        model = User
        fields = '__all__'
#    fields = ('field1','field2')

firstapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from firstapp.models import User
from firstapp.forms import NewformPage
from . import forms


def home(request):
    return render(request,'home.html')

def homepage(request):
    return HttpResponse("Welcome to Django Development")

def index(request):
    mydict = {'insert':"Inserted from views"}
    return render(request,'index.html',context=mydict)
def help(request):
    mydict = {'insert':"User is Registered"}
    return render(request,'help.html', context=mydict)

def users(request):

    users_list = User.objects.order_by('fname')
    dict = {"User_Data":users_list}
    return render(request,'users.html',context=dict)

def form_name_view(request):
    form = forms.FormName()

    if request.method == 'POST':

        form = forms.FormName(request.POST)
        if form.is_valid():
            print('NAME:'+form.cleaned_data['name'])
            print('EMAIL:'+form.cleaned_data['email'])

    return render(request,'forms/form_page.html',{'form':form})

def formdataSave(request):

    user = forms.NewformPage()

    if request.method == 'POST':
        user = NewformPage(request.POST)
        if user.is_valid():
            user.save(commit=True)
            return index(request)
        else:
            print("Invalid user")

    return render(request,'forms/form_page.html',{'form':user})

learnURL/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def index(request):
    return render(request,'learnURL/homepage.html')

def other(request):
    return render(request,'learnURL/other.html')

def relative(request):
    return render(request,'learnURL/relative.html')

def home(request):
    return HttpResponse("New APP learnURL")

templates/firstapp/help.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<em>{{ insert }}</em>
</body>
</html>

templates/firstapp/home.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Page Title</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
  box-sizing: border-box;
}

/* Style the body */
body {
  font-family: Arial, Helvetica, sans-serif;
  margin: 0;
}

/* Header/logo Title */
.header {
  padding: 80px;
  text-align: center;
  background: #1abc9c;
  color: white;
}

/* Increase the font size of the heading */
.header h1 {
  font-size: 40px;
}

/* Style the top navigation bar */
.navbar {
  overflow: hidden;
  background-color: #333;
}

/* Style the navigation bar links */
.navbar a {
  float: left;
  display: block;
  color: white;
  text-align: center;
  padding: 14px 20px;
  text-decoration: none;
}

/* Right-aligned link */
.navbar a.right {
  float: right;
}

/* Change color on hover */
.navbar a:hover {
  background-color: #ddd;
  color: black;
}

/* Column container */
.row {
  display: -ms-flexbox; /* IE10 */
  display: flex;
  -ms-flex-wrap: wrap; /* IE10 */
  flex-wrap: wrap;
}

/* Create two unequal columns that sits next to each other */
/* Sidebar/left column */
.side {
  -ms-flex: 30%; /* IE10 */
  flex: 30%;
  background-color: #f1f1f1;
  padding: 20px;
}

/* Main column */
.main {
  -ms-flex: 70%; /* IE10 */
  flex: 70%;
  background-color: white;
  padding: 20px;
}

/* Fake image, just for this example */
.fakeimg {
  background-color: #aaa;
  width: 100%;
  padding: 20px;
}

/* Footer */
.footer {
  padding: 20px;
  text-align: center;
  background: #ddd;
}

/* Responsive layout - when the screen is less than 700px wide, make the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 700px) {
  .row {
    flex-direction: column;
  }
}

/* Responsive layout - when the screen is less than 400px wide, make the navigation links stack on top of each other instead of next to each other */
@media screen and (max-width: 400px) {
  .navbar a {
    float: none;
    width: 100%;
  }
}
</style>
</head>
<body>

<div class="header">
  <h1>My Website</h1>
  <p>A website created by me.</p>
</div>

<div class="navbar">
  <a href="#">Link</a>
  <a href="#">Link</a>
  <a href="#">Link</a>
  <a href="#" class="right">Link</a>
</div>

<div class="row">
  <div class="side">
    <h2>About Me</h2>
    <h5>Photo of me:</h5>
    <div class="fakeimg" style="height:200px;">Image</div>
    <p>Some text about me in culpa qui officia deserunt mollit anim..</p>
    <h3>More Text</h3>
    <p>Lorem ipsum dolor sit ame.</p>
    <div class="fakeimg" style="height:60px;">Image</div><br>
    <div class="fakeimg" style="height:60px;">Image</div><br>
    <div class="fakeimg" style="height:60px;">Image</div>
  </div>
  <div class="main">
    <h2>TITLE HEADING</h2>
    <h5>Title description, Dec 7, 2017</h5>
    <div class="fakeimg" style="height:200px;">Image</div>
    <p>Some text..</p>
    <p>Sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
    <br>
    <h2>TITLE HEADING</h2>
    <h5>Title description, Sep 2, 2017</h5>
    <div class="fakeimg" style="height:200px;">Image</div>
    <p>Some text..</p>
    <p>Sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
  </div>
</div>

<div class="footer">
  <h2>Footer</h2>
</div>

</body>
</html>

templates/firstapp/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static "css/mystyle.css" %}"/>
    <h1>USER REGISTERED!!!!</h1>
</head>
<body>

<img src="{% static "images/test.jpg" %}" alt="Didn't load" >
</body>
</html>

templates/firstapp/users.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Info</title>
    <link rel="stylesheet" href="{% static "css/mystyle.css" %}"/>
    <link rel="stylesheet" href="{% static "css/mystyle.css" %}"/>

    <h1>Users are Listed Below</h1>
</head>
<body>

    {% if User_Data %}
    <ol>
        {% for i in User_Data %}
            <li>User Info</li>
            <ul>
                <li>First Name: {{ i.fname }}</li>
                <li>Last Name: {{ i.lname }}</li>
                <li>Email : {{ i.email }}</li>
            </ul>

        {% endfor %}
    </ol>
    {% endif %}
</body>
</html>

templates/forms/form_page.html
<!DOCTYPE html>
<html>
<style>
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box}

/* Full-width input fields */
input[type=text], input[type=password] {
  width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}

hr {
  border: 1px solid #f1f1f1;
  margin-bottom: 25px;
}

/* Set a style for all buttons */
button {
  background-color: #04AA6D;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

button:hover {
  opacity:1;
}

/* Extra styles for the cancel button */
.cancelbtn {
  padding: 14px 20px;
  background-color: #f44336;
}

/* Float cancel and signup buttons and add an equal width */
.cancelbtn, .signupbtn {
  float: left;
  width: 50%;
}

/* Add padding to container elements */
.container {
  padding: 16px;
}

/* Clear floats */
.clearfix::after {
  content: "";
  clear: both;
  display: table;
}

/* Change styles for cancel button and signup button on extra small screens */
@media screen and (max-width: 300px) {
  .cancelbtn, .signupbtn {
     width: 100%;
  }
}
</style>
<body>

<form method="post" style="border:1px solid #ccc">
  <div class="container">
    <h1>Sign Up</h1>
    <p>Please fill in this form to create an account.</p>
    <hr>
    {{ form.as_p }}
      {% csrf_token %}

    <div class="clearfix">
      <input type="submit" class="signupbtn">Sign Up</input>
    </div>
  </div>
</form>

</body>
</html>

templates/learnURL/base.html
<!Doctype Html>
<Html>
<Head>
<Title>
Make a Navigation Bar
</Title>
<style type=text/css>
body
{
height: 125vh;
margin-top: 80px;
padding: 30px;
background-size: cover;
font-family: sans-serif;
}
header {
background-color: orange;
position: fixed;
left: 0;
right: 0;
top: 5px;
height: 30px;
display: flex;
align-items: center;
box-shadow: 0 0 25px 0 black;
}
header * {
display: inline;
}
header li {
margin: 20px;
}
header li a {
color: blue;
text-decoration: none;
}
</style>
</Head>
<Body>
<header>
<nav>
<ul>
<li>
<a href=""> Home </a>
</li>
<li>
<a href="{% url 'learnURL:relative' %}"> other </a>
</li>
<li>
<a href="{% url 'learnURL:other' %}"> Relative </a>
</li>
<li> <a href="#"> Help </a>
</li>
<li>
<a href="#"> FormPage </a>
</li>
    <li>
<a href="#"> Join Us </a>
</li>
</ul>
</nav>
</header>
  {% block body_block %}
  {% endblock %}
</Body>
</Html>

templates/learnURL/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
<h1>THIS IS FROM learnURL</h1>
<a href="{% url 'learnURL:other' %}">LINK TO THE OTHER_TEMPLATE</a>
</body>
</html>

templates/learnURL/other.html
<!DOCTYPE html>
{% extends "learnURL/base.html" %}
{% block body_block %}
<b>COMING FROM OTHER TEMPLATE</b>
{% endblock %}

templates/learnURL/relative.html
<!DOCTYPE html>
{% extends "templates/base.html" %}
{% block body_block %}
<h1>Coming from relative</h1>
{% endblock %}